title = "Phil Kershaw"
baseURL = "https://phil.kershaw.ooo"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  css = ["css/custom.css"]

[permalinks]
  "/" = "/:filename"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
