baseURL = "http://phil.kershaw.ooo/"
languageCode = "en-gb"
title = "Curriculum Vitae for Phil Kershaw"
theme = "after-dark"
[params.hackcss]
  palette = "dark-grey"
[markup.goldmark.renderer]
  unsafe= true
